### ISSUE TITLE
add icons for Mastodon and Pixelfed to rel=me widget

### ISSUE THREAD

**Issue by skyfaller** [indieweb/wordpress-indieweb#120]
When I enter the URLs for my [Mastodon](https://github.com/tootsuite/mastodon) and  [Pixelfed](https://github.com/pixelfed/pixelfed) profiles to the "Other Sites" field on my Wordpress profile page, and then put the "Rel=Me Links" widget in my Wordpress sidebar, the icons for Mastodon and Pixelfed are just generic web icons rather than icons specific to Mastodon and Pixelfed.

![sad relme icons](https://user-images.githubusercontent.com/80093/46260061-5e95da00-c4af-11e8-8d98-9a443fb312e0.png)

Can we add specific fields for Mastodon and Pixelfed to the Wordpress profile page, and add the relevant icons, so that they don't look sad in the rel-me widget next to the icons for Github, Twitter etc.?

Mastodon Logo:
https://jawns.club/packs/logo-fe5141d38a25f50068b4c69b77ca1ec8.svg
https://github.com/tootsuite/mastodon/blob/master/app/javascript/images/logo.svg
https://fontawesome.com/icons/mastodon?style=brands

Pixelfed logo:
https://pixelfed.social/img/pixelfed-icon-color.svg
https://github.com/pixelfed/pixelfed/blob/dev/public/img/pixelfed-icon-color.svg

**Comment by dshanske** [comment]
@skyfaller We use an icon library any requests for specific icons can be made to them. It's easier than bundling custom icons for everything, which I used to do. https://simpleicons.org . 

For Mastodon, we have the icon. But the issue being mapping the URL of arbitrary mastodon sites to an issue. Originally, we picked the first custom profile ones based on what IndieAuth.com and Brid.gy supported, on the basis those were two services people interested in the Indieweb were using, and then recently I put in micro.blog as they directly do something with rel-me and are an Indieweb friendly provider.

On that basis, I'm closing the icon issue, but I will add a separate issue re adding a mastodon profile option here. 

As for Pixelfed... https://github.com/simple-icons/simple-icons/issues/967 They declined.

**Comment by bekoli** [comment]
For the impatient: I implemented #120 with CSS override:

![image](https://user-images.githubusercontent.com/5016428/63805408-a91b1300-c919-11e9-8dc5-61fc0ae2f001.png)

Requires Syndication Links (using it's SVGs) but you get the idea:

```css
.icon-social\.tchncs\.de  > .svg-website svg g,
.icon-git\.maxr\.org  > .svg-website svg g,
.icon-steamcommunity\.com > .svg-website svg g {
    visibility: hidden;
}
.icon-social\.tchncs\.de > .svg-website svg {
    background: url('/wp-content/plugins/syndication-links/svgs/mastodon.svg') center / contain no-repeat;
}

.icon-steamcommunity\.com > .svg-website svg {
    background: url('/wp-content/plugins/syndication-links/svgs/steam.svg') center / contain no-repeat;
}

.icon-git\.maxr\.org  > .svg-website svg {
    background: url('/wp-content/plugins/syndication-links/svgs/gitlab.svg') center / contain no-repeat orange;
    mask: orange!important;
}

.icon-social\.tchncs\.de > .svg-website svg:hover,
.icon-steamcommunity\.com > .svg-website svg:hover,
.icon-git\.maxr\.org  > .svg-website svg:hover {
    /* mimic a:hover effect */
    filter: opacity(0.5)
}
```
Tested in recent FF, Chrome and IE11. Fair enough for me.
